version: 2

models:
  - name: stg_orders
    columns:
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
